#!/bin/bash
#Set job requirements
#SBATCH -N 1
#SBATCH -t 15:00

#iRODS + Python
module load pre2019
module load icommands
module load Python
cd /home/<FILL IN>/iRODS-Compute-Tutorial-ACES

#parameters for iRODS connection
export HOST=<FILL IN>
export PORT=1247
export USER=<FILL IN>
export PASSWORD=<FILL IN>
export ZONE=<FILL IN>

#iRODS user to share results with
export SHARE=<FILL IN>

#download reference data
wget -P $TMPDIR/<FILL IN> https://ndownloader.figshare.com/files/4851460
export DATAPATH=$TMPDIR/<FILL IN>/4851460

#if you only want to calculate tokens of a certain algorithm (Random, Single, Lee)
export ALGO=

# call the program
python acesWorkflow.py > /home/<FILL IN>/iRODS-Compute-Tutorial-ACES/outputjob_aces
